In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('olympics.csv')

In [3]:
print(data.columns)

Index(['Year', 'City', 'Sport', 'Discipline', 'NOC', 'Event', 'Gender',
       'Medal', 'Country', 'Latitude', 'Longitude'],
      dtype='object')

In [4]:
data.Country.unique()

array(['Austria', 'Belgium', 'Canada', 'Finland', 'France',
       'United Kingdom', 'Norway', 'Switzerland', 'Sweden',
       'United States', 'Germany', 'Czechoslovakia', 'Hungary', 'Italy',
       'West Germany', 'Netherlands', 'Unified Team of Germany', 'Japan',
       'Poland', 'Soviet Union', 'Korea, North', 'East Germany',
       'Romania', 'Spain', 'Liechtenstein', 'Bulgaria', 'Yugoslavia',
       'China', 'Unified Team', 'Korea, South', 'Luxembourg',
       'New Zealand', 'Australia', 'Belarus', 'Kazakhstan', 'Russia',
       'Slovenia', 'Ukraine', 'Uzbekistan', 'Czech Republic', 'Denmark',
       'Croatia', 'Estonia', 'Latvia', 'Slovakia'], dtype=object)

In [5]:
countries = {'Austria': 'Europe, West',
              'Belgium': 'Europe, West',
              'Canada': 'America, North',
              'Finland': 'Europe, North',
              'France': 'Europe, West',
              'United Kingdom': 'Europe, North',
              'Norway': 'Europe, North',
              'Switzerland': 'Europe, West',
              'Sweden': 'Europe, North',
              'United States': 'America, North',
              'Germany': 'Europe, West',
              'Czechoslovakia': 'Europe, East',
              'Hungary': 'Europe, East',
              'Italy': 'Europe, South',
              'West Germany': 'Europe, West',
              'Netherlands': 'Europe, West',
              'Unified Team of Germany': 'Europe, West',
              'Japan': 'Asia, East',
              'Poland': 'Europe, East',
              'Soviet Union': 'Europe, East',
              'Korea, North': 'Asia, East',
              'Easy Germany': 'Europe, West',
              'Romania': 'Europe, East',
              'Spain': 'Europe, South',
              'Liechtenstein': 'Europe, West',
              'Bulgaria': 'Europe, East',
              'Yugoslavia': 'Europe, East',
              'China': 'Asia, East',
              'Unified Team': 'Other',
              'Korea, South': 'Asia, East',
              'Luxembourg': 'Europe, West',
              'New Zealand': 'Australasia',
              'Australia': 'Australasia',
              'Belarus': 'Europe, East',
              'Kazakstan': 'Asia, Central',
              'Russia': 'Europe, East',
              'Slovenia': 'Europe, South',
              'Ukraine': 'Europe, East',
              'Uzbekistan': 'Asia, Central',
              'Czech Republic': 'Europe, East',
              'Denmark': 'Europe, North',
              'Croatia': 'Europe, South',
              'Estonia': 'Europe, North',
              'Latvia': 'Europe, North',
              'Slovakia': 'Europe, East'}
regions = ['Africa, East',
           'Africa, Middle',
           'Africa, North',
           'Africa, South',
           'Africa, West',
           'Caribbean',
           'America, Central',
           'America, North',
           'America, South',
           'Asia, Central',
           'Asia, East',
           'Asia, South-East',
           'Asia, South',
           'Asia, West',
           'Europe, East',
           'Europe, North',
           'Europe, South',
           'Europe, West',
           'Australasia',
           'Melanesia',
           'Micronesia',
           'Polynesia']

In [6]:
data['Region'] = data['Country'].map(countries)
totals = data['Region'].value_counts().to_dict()
totals

{'Europe, West': 698,
 'Europe, North': 578,
 'Europe, East': 342,
 'America, North': 335,
 'Europe, South': 114,
 'Asia, East': 98,
 'Other': 23,
 'Australasia': 7,
 'Asia, Central': 1}

In [7]:
df = pd.DataFrame(columns=['Total'], index=regions)

In [8]:
for k, v in totals.items():
    df['Total'].loc[k] = v
    
for i in data['Year'].unique():
    totals = data[data['Year']==i]['Region'].value_counts()
    df[i] = 0
    for k, v in totals.items():
        df[i].loc[k] = v

/var/folders/z0/6xgjsnpn1qncl3w0nx4w7_d40000gn/T/ipykernel_2185/134598172.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i].loc[k] = v
/var/folders/z0/6xgjsnpn1qncl3w0nx4w7_d40000gn/T/ipykernel_2185/134598172.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i].loc[k] = v
/var/folders/z0/6xgjsnpn1qncl3w0nx4w7_d40000gn/T/ipykernel_2185/134598172.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i].loc[k] = v
/var/folders/z0/6xgjsnpn1qncl3w0nx4w7_d40000gn/T/ipykernel_2185/134598172.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i].loc[k] = v
/var/folders/z0/6xgjsnpn1qncl3w0nx4w7_d40000gn/T/ipykernel_2185/134598172.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i].loc[k] = v
/var/folders/z0/6xgjsnpn1qncl3w0nx4w7_d40000gn/T/ipykernel_2185/134598172.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i].loc[k] = v
/var/folders/z0/6xgjsnpn1qncl3w0nx4w7_d40000gn/T/ipykernel_2185/134598172.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i].loc[k] = v
/var/folders/z0/6xgjsnpn1qncl3w0nx4w7_d40000gn/T/ipykernel_2185/134598172.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i].loc[k] = v
/var/folders/z0/6xgjsnpn1qncl3w0nx4w7_d40000gn/T/ipykernel_2185/134598172.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i].loc[k] = v
/var/folders/z0/6xgjsnpn1qncl3w0nx4w7_d40000gn/T/ipykernel_2185/134598172.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i].loc[k] = v
/var/folders/z0/6xgjsnpn1qncl3w0nx4w7_d40000gn/T/ipykernel_2185/134598172.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i].loc[k] = v
/var/folders/z0/6xgjsnpn1qncl3w0nx4w7_d40000gn/T/ipykernel_2185/134598172.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i].loc[k] = v
/var/folders/z0/6xgjsnpn1qncl3w0nx4w7_d40000gn/T/ipykernel_2185/134598172.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i].loc[k] = v
/var/folders/z0/6xgjsnpn1qncl3w0nx4w7_d40000gn/T/ipykernel_2185/134598172.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i].loc[k] = v
/var/folders/z0/6xgjsnpn1qncl3w0nx4w7_d40000gn/T/ipykernel_2185/134598172.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i].loc[k] = v
/var/folders/z0/6xgjsnpn1qncl3w0nx4w7_d40000gn/T/ipykernel_2185/134598172.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i].loc[k] = v
/var/folders/z0/6xgjsnpn1qncl3w0nx4w7_d40000gn/T/ipykernel_2185/134598172.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i].loc[k] = v
/var/folders/z0/6xgjsnpn1qncl3w0nx4w7_d40000gn/T/ipykernel_2185/134598172.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i].loc[k] = v
/var/folders/z0/6xgjsnpn1qncl3w0nx4w7_d40000gn/T/ipykernel_2185/134598172.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i].loc[k] = v
/var/folders/z0/6xgjsnpn1qncl3w0nx4w7_d40000gn/T/ipykernel_2185/134598172.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i].loc[k] = v
/var/folders/z0/6xgjsnpn1qncl3w0nx4w7_d40000gn/T/ipykernel_2185/134598172.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i].loc[k] = v

In [9]:
df.fillna(0, inplace=True)

In [10]:
df

,Total,1924,1928,1932,1936,1948,1952,1956,1960,1964,...,1972,1976,1980,1984,1988,1992,1994,1998,2002,2006
"Africa, East",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
"Africa, Middle",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
"Africa, North",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
"Africa, South",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
"Africa, West",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Caribbean,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
"America, Central",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
"America, North",335,5,7,19,5,12,13,10,14,9,...,9,13,14,12,11,18,26,28,51,49
"America, South",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
"Asia, Central",1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
"Asia, East",98,0,0,0,0,0,0,1,0,1,...,3,0,1,1,1,15,14,24,14,23
"Asia, South-East",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
"Asia, South",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
"Asia, West",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
"Europe, East",342,0,1,1,1,2,1,18,24,26,...,20,28,25,32,35,3,27,25,22,33
"Europe, North",578,34,25,16,31,28,30,21,21,33,...,21,17,24,31,18,31,37,42,44,47
"Europe, South",114,0,0,0,0,1,2,3,1,4,...,6,4,2,2,5,15,23,10,18,14
"Europe, West",698,10,8,6,14,25,21,19,21,30,...,32,30,26,15,43,65,51,73,83,84
Australasia,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,1,2,2
Melanesia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Micronesia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Polynesia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
df.to_csv('total.csv')